spring:

  application:
    name: cloudchat-backend
    config:
    import: optional:file:.env
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      host: 127.0.0.1
      port: 6379
      ssl:
        enabled: false
        time-to-live: 900000

software:
  jwt:
    access:
      secret: ${JWT_ACCESS_SECRET}
      life: ${JWT_ACCESS_LIFE}
    refresh:
      secret: ${JWT_REFRESH_SECRET}
      life: ${JWT_REFRESH_LIFE}
  cros:
    allowed-origin: https://fluffy-lolly-682538.netlify.app, http://localhost:3000
  
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.sopvlight.cloudchat_backend: DEBUG
  file:
    name: logs/cloudchat-backend.log
    max-size: 100MB
    max-history: 1000
